language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install ply
script:
    - python -m pytest --doctest-modules --cov-report term-missing --cov . --ignore pype/driver.py
after_success:
    - coveralls
